objects/Customer_Satisfaction_Survey__c.object
<CustomObject>
    <fields>
        <fullName>AutorabitExtId__c</fullName>
        <description>External Id created by AutoRABIT</description>
        <externalId>true</externalId>
        <label>AutorabitExtId__c</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Customer Satisfaction Survey</label>
    <nameField>
        <label>Customer Satisfaction Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Satisfaction Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Customer_Satisfaction_Survey_2.cls
public class Customer_Satisfaction_Survey_2 {
    
      public Customer_Satisfaction_Survey__c Customer;
    
    Public Customer_Satisfaction_Survey_2(Apexpages.StandardController controller){
        Customer =new Customer_Satisfaction_Survey__c() ;
    }
    
    public pageReference Survey(){ 
        Customer.Name=Customer.Name;
        Customer.AutorabitExtId__c=Customer.AutorabitExtId__c;
        return null;
    }
}